---
- name: Create user profile on IBM i
  hosts: all
  gather_facts: no

  vars:
    users:
       - GEORGE
       - JANE

  tasks:
    - name: Prompt for user name if not yet defined  
      block:
      - pause:
          prompt: "Enter User Name"
        register: entered
      - set_fact:
          user_name: "{{ entered.user_input }}"
      when: user_name is undefined

    - name: collect user profile information
      ibm.power_ibmi.ibmi_user_and_group:
        operation: 'display'
        user: "{{ item }}"
      loop: "{{ users }}"
      register: user_check
      ignore_errors: false

    - name: Display profiles for new users
      debug:
        msg: "{{ item.result_set }}"
      loop: "{{ user_check.results }}"
      loop_control:
        label: "{{ item }}"
