---
# tasks file for manage_ptfs

#- name: Include fix_repo_check_download_individual_ptfs role to check and download a list of individual ptfs
#  include_role:
#    name: fix_repo_check_download_individual_ptfs
#  ignore_errors: true


- name: Check PTFS  
  include_tasks: 
    - query_ptf.yml
    - show_ptf.yml
  