---
# tasks file for manage_ptfs
#- name: Include fix_repo_check_download_individual_ptfs role to check and download a list of individual ptfs
#  include_role: 
#    name: fix_repo_check_download_individual_ptfs
#  ignore_errors: true

- name: Check system for PTFs  
  include_tasks: query_system_for_ptfs.yml
  
#- name: Find matching PTFs  
#  set_fact:
#     matching_ptfs: "{{ matching_ptfs | combine({item.PTF_IDENTIFIER: { 'PTF_INFO': item }}, recursive = true) }}"
#  loop: "{{ loaded_ptfs }}"
#  loop_control:
#    label: "{{ item.PTF_IDENTIFIER }}"
#  when: item.PTF_IDENTIFIER in ptfs_list   

#- set_fact:
#    matching_ptfs: "{{ matching_ptfs | combine({item: { 'PTF_INFO': loaded_ptfs[idx] }}, recursive = true) }}"
#  vars:
- debug:
    msg: "{{ loaded_ptfs | ansible.utils.index_of('eq', item) }}"
  loop: "{{ ptfs_list }}"


- name: Show details for matching PTFs  
  include_tasks: show_ptf_details.yml
  vars:
    product: "{{ item.PTF_PRODUCT_ID }}"
    ptf: "{{ item.PTF_IDENTIFIER }}"
    release: "{{ PTF_PRODUCT_RELEASE_LEVEL }}" 
  loop: "{{ matching_ptfs |dict2items }}"


