---
- name: deleting user profile(s)
  ibm.power_ibmi.ibmi_user_and_group:
    operation: 'delete'
    user: "{{ item.name }}"
  loop: "{{ users }}"  
  register: user_profile
  ignore_errors: false

- name: "Delete profile operation results for user: {{ user_name }}"
  debug:
    msg: "{{ user_profile.stdout}}"
      
