---
- name: Display/Show user profile information 
  hosts: all
  gather_facts: no

  tasks:
    - name: Prompt for user name if not yet defined  
      block:
      - pause:
          prompt: "Enter User Name"
        register: entered
      - set_fact:
          user_name: "{{ entered.user_input }}"
      when: user_name is undefined

    - name: collect user profile information
      ibm.power_ibmi.ibmi_user_and_group:
        operation: 'display'
        user: "{{ user_name }}"
      register: user_profile
      ignore_errors: false

    - name: "Display profile for user: {{ user_name }}"
      debug:
        msg: "{{ user_profile.result_set}}"
      
