--- 
- name: get list of authorized users 
  ibm.power_ibmi.ibmi_cl_command:
    cmd: 'DSPAUTUSR'
  register: auth_users

- name: display authorized users
  debug:
    msg: "{{ auth_users.stdout.split('\n') }}"

 


