--- 

- name: Query list of authorized users 
  command: 'system "DSPAUTUSR"'
  register: auth_users
  changed_when: false

- name: Display profiles for new users
  debug:
    msg: "{{ auth_users.stdout.split('\n') }}"

- name: List authorized users 
  ibmi_cl_command:
    cmd: 'DSPAUTUSR'
  register: auth_user

- name: Display profiles for new users
  debug:
    msg: "{{ auth_users.stdout }}"

 


