---
# tasks file for manage_users

- name: "{{ user_action }} user profile(s)" 
  include_tasks: "{{ user_action }}_profile.yml"
  when: user_action in valid_actions
  vars: 
    valid_actions:
      - add
      - delete
      - show
      - update
      - verify
      - list_auth
