---
- name: Do user profile compliance check
  ibm.power_ibmi.ibmi_user_compliance_check:
    joblog: true
    users: "{{ users }}"    
    fields: "{{ check_for }}"
  register: comp_check

- name: Display results 
  debug:
    msg: "{{ comp_check.result_set }}"

