---
- name: Load user names
  set_fact:
     users_to_verify: "{{ users_to_verify |default([]) + [item.name] }}"
  loop: "{{ users }} "   


- name: compliance check
  ibm.power_ibmi.ibmi_user_compliance_check:
    joblog: true
    users: "{{ users_to_verify }}"    
    fields: "{{ compliance_check_list }}"
  register: comp_check

- name: Display results 
  debug:
    msg: "{{ comp_check.result_set }}"